#Aprende a hacer makefiles mas generales. Aqui "$<" es el primero en la lista
# De las dependencias y $@ es el nombre antes de los dos puntos en el primer renglon.
# Existe tambien la abreviacion $^ que quiere decir todo a la derecha de los dos puntos
# en el renglon de las dependencias.

MapaHoyos01.x: MapeandoHoyos01.cpp simplectic01.hpp ReglasDinamicas01.hpp
	g++ -O2 $< -o $@


